# Generated by Django 6.0.3 on 2026-04-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sign_in_time', models.DateTimeField(blank=True, null=True)),
                ('sign_in_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/in/')),
                ('sign_in_location', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('sign_out_photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/out/')),
                ('sign_out_location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Absent', max_length=20)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total worked hours', max_digits=5, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
